### ISSUE TITLE
Ability to specify stream type

### ISSUE THREAD

**Issue by dnabb** [arnoN7/dbt-incremental-stream#14]
Snowflake supports [multiple types of streams](https://docs.snowflake.com/en/user-guide/streams-intro#types-of-streams).

In some cases, using a stream type other than the standard can be beneficial: as example, append-only stream are more performant than standard streams.

It would be nice if it were possible to specify the type of stream to be created by dbt, ideally as an optional argument to the stream_ref / stream_source macros.

**Comment by arnoN7** [comment]
That's a great point! I'll look into adding it and will update here once I've made progress.

**Comment by arnoN7** [comment]
As suggested, I've added an optional `stream_type` argument to the `stream_ref` and `stream_source` macros, allowing you to specify the desired stream type directly (`STANDARD`, `APPEND_ONLY` or `INSERT_ONLY`). The default value is `STANDARD`. I'd love to hear your feedback if you get a chance to try it out in your project!
