### ISSUE TITLE
Feature request: ability to set OFFSET variable

### ISSUE THREAD

**Issue by ramandatascientist** [arnoN7/dbt-incremental-stream#3]
- I like to request to have a feature that can handle `TIMESTAMP` variable in a steam
- https://docs.snowflake.com/en/sql-reference/sql/create-stream#using-time-travel-with-the-source-table
- example: if i want to reload the data from from August 1, then this package should recreate streams )
-  eg: `dbt run --vars {{TIMESTAMP: '01/08/2023 00:00:00'}}`
`- CREATE STREAM mystream ON TABLE mytable AT (TIMESTAMP => TO_TIMESTAMP_TZ('TIMESTAMP: '01/08/2023 00:00:00', 'mm/dd/yyyy hh24:mi:ss'));`
- If this variable is not defined, then stream should work naturally (without any offset)
- This feature will help users to reload/reprocess historical data from any point in time during any incidents etc (a very common use case in our company and other customers as well)

**Comment by arnoN7** [comment]
TIMESTAMP var is now supported
