### ISSUE TITLE
Aggregating stream data

### ISSUE THREAD

**Issue by sternalon** [arnoN7/dbt-incremental-stream#6]
I am looking to consume data from a stream, and then aggregate it before merging it into another table. How can this be done using incremental_streams

Here is some pseudo code:

_______________________________________________________
{{
    config(
        materialized='incremental_stream',
        unique_key=['key']
    )
}}

WITH 
new_data AS ( 
           SELECT 
                 key, 
                value
                {{ incr_stream.get_stream_metadata_columns() }}
 from {{incr_stream.stream_source('src', 'table')}}
),

aggregated_data AS (
Select key
           Max(value)
from new_data
Group by key

Select * from aggregated_data

_______________________________________________________

The problem is that the get_stream_metadata_columns()  are not included in the aggregation.

Is there any way around this?

**Comment by arnoN7** [comment]
Hi @sternalon,

Apologies for the delay in getting back to you.

What you're attempting to achieve—incrementally updating aggregated data—can indeed be complex. I would suggest considering the use of [❄️ dynamic tables](https://docs.snowflake.com/en/user-guide/dynamic-tables-intro), which allow Snowflake to handle the updates to your aggregation automatically. Dynamic tables are well-suited for this type of incremental processing.

However, if you prefer to stick with streams, I would recommend the following approach, which avoids directly aggregating the data but allows incremental_stream to handle the changes (inserts, updates, or deletes) based on the new rows and existing data:
```
{{
config(
  materialized='incremental_stream',
  unique_key=['key']
)
}}

WITH new_data AS (
  SELECT
    key,
    value
    {{ incr_stream.get_stream_metadata_columns() }}
  FROM {{ incr_stream.stream_source('src', 'table') }}
),

aggregated_data AS (
  SELECT
    key,
    MAX(value) OVER (PARTITION BY key) AS value
    {{ incr_stream.get_stream_metadata_columns() }}
  FROM new_data
)

SELECT * FROM aggregated_data;
```
This version does not directly aggregate data in the way you may initially expect (with a `GROUP BY` clause). Instead, it uses a window function to ensure you maintain access to the stream's metadata columns in the output. This allows for more flexibility in handling incremental updates without losing the ability to track the metadata alongside the new data.

I hope this helps, but feel free to reach out if you'd like further clarification or assistance!
