### ISSUE TITLE
Cannot create streams on a view

### ISSUE THREAD

**Issue by robscriva** [arnoN7/dbt-incremental-stream#8]
There is no option to work with a [view](https://docs.snowflake.com/en/user-guide/streams-intro#streams-on-views) as [TABLE has been hardcoded](https://github.com/arnoN7/dbt-incremental-stream/blob/master/macros/materializations/incremental_stream.sql#L40).

Throws the error:
```
002203 (02000): SQL compilation error: Object found is of type 'VIEW', not specified type 'TABLE'.
```

**Comment by arnoN7** [comment]
Hi @robscriva I merge your fix code to create streams based on table or view. Also add a unit test. Be careful if you use `incr_stream.stream_ref('a_view_model')` once you run the view model again it breaks the stream. If you recreate the view you need to do a --full-refresh on the incremental_stream model.
